version: "3.7"

services:
    dockerRegistry:
        container_name: registry
        image: registry:2
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - v-registry:/var/lib/registry
        networks:
            - ci
    jenkinsMaster:
        container_name: jenkinsMaster
        image: silicom/jenkins-master:1
        restart: always
        privileged: true
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - v-jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
 #           - v-vvv:/usr/bin/docker
        networks:
            - ci
        depends_on:
            - nexus
        environment:
            - NEXUS_PORT=8081
    jenkinsSlave1:
        container_name: jenkinsSlave1
        image: silicom/ubuntu18:latest
        restart: always
        ports:
            - "2221:22"
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    #        - v-vvv:/usr/bin/docker
        depends_on:
            - jenkinsMaster
        networks:
            - ci
    jenkinsSlave2:
        container_name: jenkinsSlave2
        image: silicom/ubuntu18:latest
        restart: always
        ports:
            - "2222:22"
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkinsMaster
        networks:
            - ci
            
    nexus:
        container_name: nexus
        image: sonatype/nexus3
        restart: always
        ports:
            - "8081:8081"
        volumes:
            - v-nexus:/nexus-data
        networks:
            - ci

volumes:
    v-jenkins:
    v-nexus:
    v-registry:
    v-vvv:

networks:
    ci:
        driver: bridge