version: "3.7"

services:
    jenkinsMaster:
        container_name: jenkinsMaster
        image: silicom/jenkins-master:1
        restart: always
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - v-jenkins:/var/jenkins_home
        networks:
            - ci
        depends_on:
            - nexus
        environment:
            - NEXUS_PORT=8081
    jenkinsSlave:
        container_name: jenkinsSlave
        image: silicom/ubuntu18:latest
        restart: always
        ports:
            - "2222:22"
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
#            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
        depends_on:
            - jenkinsMaster
        networks:
            - ci
            
    nexus:
        container_name: nexus
        image: sonatype/nexus3
        restart: always
        ports:
            - "8081:8081"
        volumes:
#            - /etc/nexus/nexus-data:/nexus-data
            - v-nexus:/nexus-data
        networks:
            - ci

volumes:
    v-jenkins:
#    nexus-data: {}
    v-nexus:

networks:
    ci:
        driver: bridge